
-- Add extended fields to properties table
ALTER TABLE properties
ADD COLUMN IF NOT EXISTS case_number TEXT,
ADD COLUMN IF NOT EXISTS listing_type TEXT,
ADD COLUMN IF NOT EXISTS auction_time TEXT,
ADD COLUMN IF NOT EXISTS auction_venue TEXT,
ADD COLUMN IF NOT EXISTS address_lot_number TEXT,
ADD COLUMN IF NOT EXISTS size_m2 TEXT,
ADD COLUMN IF NOT EXISTS title_deed_number TEXT,
ADD COLUMN IF NOT EXISTS bedrooms INTEGER,
ADD COLUMN IF NOT EXISTS terms_of_sale TEXT,
ADD COLUMN IF NOT EXISTS seller_contact_entity TEXT,
ADD COLUMN IF NOT EXISTS contact_numbers TEXT,
ADD COLUMN IF NOT EXISTS attorney TEXT,
ADD COLUMN IF NOT EXISTS plaintiff TEXT,
ADD COLUMN IF NOT EXISTS defendant_owner TEXT,
ADD COLUMN IF NOT EXISTS notice_date DATE;
